project:
  type: book

book:
  chapters:
    - file: "index.qmd"
    - file: "intro.qmd"
    - file: "aim1.qmd"
    - file: "aim2.qmd"
    - file: "aim3.qmd"
    - file: "conclusion.qmd"
    - file: "refs.qmd"
  appendices:
    - file: "appendixA.qmd"
    - file: "appendixB.qmd"
    - file: "appendixC.qmd"


bibliography: references.bib
csl: american-statistical-association.csl
degreetype: Doctor of Philosophy
submitted: 2024
affiliation: Department of Population Health
#degrees: 'B.S. Mathematics, Case Western Reserve University'

format:
  pdf:
    pdf-engine: xelatex
    classoption: oneside
    toc: false
    number-sections: false
    #template: template.tex
    header-includes: |
       \usepackage{setspace}
       \doublespacing
       \usepackage{fancyhdr}
       \pagestyle{fancy}
       \fancyhf{}
       \fancyhead[R]{\thepage}
       \fancyhead[R]{\thepage}
       \renewcommand{\thepage}{\arabic{page}} % Use Arabic numerals for main pages
       \renewcommand{\headrulewidth}{0pt}
       \renewcommand{\footrulewidth}{0pt}
       \usepackage{etoolbox}
       \makeatletter
       \patchcmd{\chapter}{\cleardoublepage}{\clearpage}{}{}
       \makeatother
       \fancypagestyle{plain}{ % Redefine the "plain" style used for chapter pages
         \fancyhf{} % Clear all headers and footers
         \fancyhead[R]{\thepage} % Add page number to the top-right corner
         \renewcommand{\headrulewidth}{0pt} % Remove header line
         \renewcommand{\footrulewidth}{0pt} % Remove footer line
       }
       \usepackage{etoolbox}
       \makeatletter
       \patchcmd{\chapter}{\thispagestyle{plain}}{\thispagestyle{fancy}}{}{}
       \makeatother


