project:
  type: book

book:
  chapters:
  #  - text: "Title Page"
  #    file:
    - "index.qmd"
    - "intro.qmd"
    - "aim1.qmd"
    - "aim2.qmd"
    - "aim3.qmd"
    - "conclusion.qmd"
    - "refs.qmd"
  appendices:
    - "appendixA.qmd"
    - "appendixB.qmd"
    - "appendixC.qmd"


bibliography: references.bib
csl: american-statistical-association.csl
degreetype: Doctor of Philosophy
submitted: 2024
affiliation: Department of Population Health
#degrees: 'B.S. Mathematics, Case Western Reserve University'

format:
  pdf:
    pdf-engine: xelatex
    classoption: oneside
    toc: false
    #template: template.tex
    header-includes:
      - \usepackage{setspace}
      - \doublespacing
      - \usepackage{fancyhdr}
      - \pagestyle{fancy}
      - \fancyhf{}
      - \fancyhead[R]{\thepage}
      - \fancyhead[R]{\thepage}
      - \renewcommand{\thepage}{\arabic{page}} % Use Arabic numerals for main pages
      - \renewcommand{\headrulewidth}{0pt}
      - \renewcommand{\footrulewidth}{0pt}
      - \usepackage{etoolbox}
      - \makeatletter
      - \patchcmd{\chapter}{\thispagestyle{plain}}{\thispagestyle{fancy}}{}{}
      - \makeatother


