---
title: "Table 5: Data sources and years"
editor: visual
---

| Variable                             | Description                                                                                 | Source                                                                | Year(s)       |
|--------------|--------------------------|------------------|--------------|
| **Poor mental health days**          | Average number of mentally unhealthy days reported in past 30 days (age-adjusted)           | Behavioral Risk Factor Surveillance System (BRFSS)                    | 2018          |
| **Percent Non-Hispanic Black**       | Percentage of the population that is non-Hispanic Black or African American                 | US Census Bureau                                                      | 2019          |
| **Percent Hispanic**                 | Percentage of the population that is Hispanic                                               | US Census Bureau                                                      | 2019          |
| **Percent over 65**                  | Percentage of the population ages 65 and older                                              | US Census Bureau                                                      | 2019          |
| **Median household income**          | The income where half of households in a county earn more and half of households earn less  | Small Area Income and Poverty Estimates (SAIPE)                       | 2019          |
| **Some college**                     | Percentage of adults ages 25–44 with some post-secondary education                          | American Community Survey (ACS)                                       | 2015–2019     |
| **Social associations**              | Number of membership associations per 10,000 population                                     | US Census, County business patterns                                   | 2018          |
| **Access to exercise opportunities** | Percentage of population with adequate access to locations for physical activity            | Business Analyst, Delorme map data, ESRI, & US Census Tigerline Files | 2010 and 2019 |
| **Food environment index**           | Index of factors that contribute to a healthy food environment, from 0 (worst) to 10 (best) | USDA Food Environment Atlas, Map the Meal Gap from Feeding America    | 2015 and 2018 |
| **Mental health providers**          | Ratio of population to mental health providers                                              | National Provider Identification file                                 | 2020          |
| **Air pollution—particulate matter** | Average daily density of fine particulate matter in micrograms per cubic meter (PM2.5)      | Environmental Public Health Tracking Network                          | 2016          |
| **Violent crime**                    | Number of reported violent crime offenses per 100,000 population                            | Uniform crime reporting—FBI                                           | 2014 and 2016 |
| **Severe housing cost burden**       | Percentage of households that spend 50% or more of their household income on housing        | American Community Survey, 5-year estimates                           | 2015–2019     |
| **Income inequality**                | Ratio of household income at the 80th percentile to income at the 20th percentile           | American Community Survey, 5-year estimates                           | 2015–2019     |

*Note*: When more than one year is reported, years were combined to create better estimates for small populations. Data and descriptions come from the 2021 CHRR publicly available dataset.
