---
title: "Introduction"
format: pdf
editor: visual
bibliography: references.bib
---

Place-based measures of health can be simplified into "contextual" and "compositional" categories. **Contextual factors** refer to the structural characteristics of a place, such as greenspace, transportation options, and access to healthcare. In contrast, **compositional factors** pertain to the characteristics of individuals within a place, including demographic attributes, behaviors, and health status [@macintyre2002a]. Though we may think of them separately, context and composition are mutually reinforcing [@cummins2007]. Contextual features (an isthmus, for example) shape the behaviors of a population (enjoyment of water and outdoor activities), and these behaviors then increase demand for additional contextual features (bike paths) which in turn affect the health of the population residing in Madison. This interdependence highlights the complexity of addressing health disparities, as interventions must consider both the characteristics of the population and the structural conditions of the place. Moreover, both types of factors are inherently linked to population migration, as they both affect and are affected by the movement of people.

The overarching goal of this dissertation is to enhance our understanding of how mobility influences place-based health. This understanding will enable local decision-makers to consider mobility patterns when formulating policies to improve health outcomes for all individuals across different locations. Throughout this dissertation, we quantify and develop methods for assessing the relationship between population mobility and place-based health measures.

This dissertation is structured around three primary aims:

1.  **Contextual Factors and Urbanicity:** The first aim focuses exclusively on contextual place-based health factors to quantify potential mediating structural factors between urbanicity and mental health.

2.  **Compositional Factors and Migration:** The second aim centers on compositional place-based health factors by examining how county-to-county migration flows impact models of county-level health.

3.  **Integration of Contextual and Compositional Factors:** The third aim examines migration as both a contextual and a compositional place-based health factor, using spatio-temporal modeling to assess how the interaction between migration patterns and local geographic context influences premature mortality rates and contributes to health inequities.

## Defining contextual measures of health

**Place**, as it relates to health, is defined not just by geographic boundaries, but by the unique set of structural and environmental characteristics that influence the health of the populations residing within them. These **contextual health factors** encompass a wide range of elements, including socioeconomic conditions, physical environment, availability of healthcare services, and social infrastructure. Understanding these factors is essential for comprehending how different places can impact health outcomes and contribute to health disparities.

Numerous studies have outlined the effects of socioeconomic conditions on health, both at the individual and place-level. Areas with higher levels of poverty, unemployment, and lower educational attainment often exhibit poorer health outcomes due to limited access to resources and opportunities that promote healthy living [@diezroux2001]. Lack of economic opportunity can lead to food insecurity, inadequate housing, and reduced access to healthcare services, all of which have direct and indirect effects on the health of communities. Additionally, even after controlling for individual-level health factors, neighborhood disadvantage has been shown to be related to higher rates of mortality and morbidity due to cardiovascular conditions [@diezroux2007; @pickett2001].

Environmental and climate-related factors also play a significant role in shaping health outcomes. Factors such as air and water quality, availability of green spaces, and exposure to pollutants can significantly influence the incidence of respiratory diseases, cardiovascular conditions, and mental health disorders. For instance, communities located near industrial sites may suffer from higher levels of pollution, which can lead to adverse health effects over time. However, environmental resources and stressors are not distributed equally, with marginalized communities, particularly people of color, disproportionately bearing the brunt of negative impacts [@environm; @banzhaf2019].

Availability and accessibility of healthcare services are another crucial contextual health factor. Places with a higher density of healthcare professionals, facilities, and services tend to have better health outcomes because residents can more easily obtain preventive care, diagnoses, and treatments and have higher rates of healthcare consumption on average [@andersen2014; @léonard2009]. One study, focused on maternal healthcare in particular, found that a one-unit increase in population density is associated with a 0.2% increase in maternal healthcare coverage rates on average[@hanlon2012]. Rural or underserved urban areas may face significant barriers to healthcare access, resulting in delayed treatments and poorer health outcomes.

Social infrastructure, including the presence of community organizations, social networks, and public health initiatives, contributes to the health of a place. Strong social cohesion and support networks can mitigate the effects of economic and environmental stressors by providing emotional support, facilitating access to information, and promoting healthy behaviors (Berkman et al., 2000). Places with robust social infrastructure can buffer against adverse health outcomes and enhance overall community well-being.

The idea of place, as conceptualized by contextual health factors, encompasses a broad array of structural and environmental elements that collectively influence the health of populations. By examining socioeconomic conditions, physical environment, healthcare availability, and social infrastructure, researchers and policymakers can better understand and address the complex determinants of health at the community level.

## Defining compositional measures of health

**Place**, when considered through the lens of **compositional health factors**, is defined by the characteristics and attributes of the individuals who inhabit it. These factors include demographic variables, socioeconomic status, health behaviors, and genetic predispositions of the population. Understanding these compositional elements is crucial for identifying how individual-level factors aggregate to influence overall health outcomes in different geographical contexts.

Demographic variables such as age, gender, race, and ethnicity are fundamental compositional factors that shape the health profile of a place. For example, communities with a higher proportion of elderly individuals may experience greater prevalence of chronic, resource intensive diseases since 79% of individuals over age 70 have at least one chronic condition [@reducing]. Additionally, female older adults living alone may be reliant on public transportation options since they are least likely to live in households with access to at least one vehicle [@li2024].

Socioeconomic status (SES) is another critical and complex compositional factor that significantly influences health outcomes. It is widely accepted that higher SES is generally associated with better health outcomes due to greater access to healthcare resources, healthier living conditions, and greater educational and employment opportunity (Adler et al., 1994). Conversely, lower SES often correlates with increased exposure to health risks and reduced access to preventive and curative healthcare services (Braveman et al., 2010), and individuals in the lowest household income quartile have self-reported rates of poor or fair health more than twice as high as individuals of the same age with incomes in the 25th through 50th percentile [@smith2004]. Additionally, there is strong correlation between high rates of income inequality and lower life expectancy across OECD countries[@kawachi1999; @commenta], and some research suggests a correlation between income inequality and high rates of obesity [@zaman2008].

Health behaviors, including diet, physical activity, smoking, and alcohol consumption, can be considered compositional factors that vary widely among populations and significantly impact health outcomes. Places where healthy behaviors are more prevalent typically exhibit lower rates of chronic diseases and higher overall life expectancy, and places where unhealthy behaviors are more prevlanet exhibit higher rates of chronic disease[@mokdad2004]. Smoking, a classic example, is causally related to cancer, meaning that communities with high rates of smoking will also have high rates of cancer [@lortet-tieulent2016]. By extension, individual health behaviors can affect place-level rates of health.

Importantly, compositional factors are inherently linked to contextual factors, with many researchers considering compositional factors as outcomes of contextual influences [@crear-perry2020; @heller2024]. For instance, socioeconomic status is often shaped by contextual factors such as the quality of local education systems, availability of job opportunities, and overall economic conditions (Kawachi & Berkman, 2003). Similarly, health behaviors are influenced by the built environment, access to preventive healthcare, access to recreational facilities, and food options (Sallis et al., 2012). This interdependence highlights the complexity of addressing health disparities, as interventions must consider both the individual characteristics of the population and the structural conditions of the place.

In summary, defining place in terms of compositional health factors involves examining the aggregate characteristics of individuals within a geographic area. Demographic variables, socioeconomic status, health behaviors, and genetic predispositions collectively shape the health outcomes of a place. By analyzing these compositional factors in combination with contextual factors, researchers and policymakers can better understand the health needs of different communities and develop targeted interventions to address specific health disparities.

## Defining Urbanicity

Urbanicity—as defined by the population density and proximity to urban centers of a place— plays a critical role in influencing health and migration patterns. **Urbanicity is both a contextual and a compositional factor** since it is directly related to both the structural resources as well as the human-related resources within a place. Urban areas, with their dense populations, advanced infrastructure, and abundant resources, offer distinct health advantages and challenges compared to rural areas. They often provide better access to healthcare, social organizations, educational, and financial opportunities, which are associated with positive health outcomes. However, urban areas may also face challenges such as limited access to green spaces, concentrated marginalized populations, crowded living conditions, and air pollution, which are linked to negative health outcomes. Migration patterns are often shaped by urbanicity, as individuals move from rural to urban areas seeking better employment, education, and healthcare. Consequently, the urban nature of a place shapes the lived experiences of its inhabitants, influencing health disparities and the overall well-being of the population. The complexity of urbanicity and its effects on health requires careful analysis to account for sociodemographic differences and unobserved confounding variables.

One theory describing the relationship between urbanicity and health is the **Urban Health Penalty Hypothesis**, which posits that urban environments can negatively impact health due to factors such as pollution, overcrowding, and high levels of stress. Urban areas often face challenges like higher crime rates, noise pollution, and exposure to environmental toxins, which can lead to adverse health outcomes, including respiratory diseases, cardiovascular conditions, and mental health disorders CITE. Migration from rural to urban areas can exacerbate these issues by increasing population density and straining existing health infrastructure, leading to reduced access to healthcare and social services.

In contrast, the **Urban Advantage Hypothesis** suggests that urban areas offer better health outcomes due to improved access to healthcare services, education, employment opportunities, and social amenities. Urban centers typically have more healthcare facilities, specialized medical services, and health professionals, which can lead to better health outcomes for residents CITE. Migration to urban areas can enhance the compositional health profile by bringing in individuals seeking better healthcare and opportunities, potentially increasing the overall health status of the urban population.

The **Social Determinants of Health Framework** emphasizes the role of socioeconomic and environmental factors in shaping health outcomes. Urban environments often present a mix of both positive and negative social determinants. On one hand, cities provide better educational and economic opportunities, which are linked to improved health outcomes. On the other hand, urban poverty, social isolation, and unequal access to resources can contribute to health disparities CITE. Migration can influence these determinants by changing the socioeconomic composition of urban areas, introducing diverse populations with varying health needs and challenges.

The **Ecological Systems Theory**, developed by Bronfenbrenner, provides a comprehensive perspective by examining how different environmental systems interact to influence individual health. This theory considers the microsystem (immediate environment), mesosystem (interactions between microsystems), exosystem (external environments that indirectly affect individuals), and macrosystem (broader cultural and social contexts) CITE. Urbanization affects these systems by altering living conditions, social networks, and access to resources. Migration contributes to these dynamics by reshaping community structures and resource allocation within urban areas.

In contrast, rural areas experiencing significant outmigration may struggle with declining economies, reduced social cohesion, and diminished public services. The **Social Disorganization Theory** suggests that such changes can lead to increased stress and mental health issues among remaining residents, as well as reduced community support and social capital, which are important determinants of health​ ([SpringerLink](https://link.springer.com/chapter/10.1007/978-3-031-18683-7_3))​. This outmigration can deplete the local workforce, including healthcare professionals, further exacerbating health disparities. The loss of younger, healthier individuals often leaves an aging population with greater health needs and fewer resources to address them.

Finally, the **Healthy Cities Movement**, supported by the World Health Organization, advocates for urban planning and policies that promote health and well-being. This approach emphasizes the importance of creating urban environments that support physical activity, provide access to healthy foods, reduce pollution, and offer safe and inclusive public spaces CITE. Migration can play a role in this movement by bringing attention to the diverse health needs of urban populations and driving initiatives to address health inequities.

The relationship between urbanicity and health is complex and influenced by both compositional changes induced by migration and contextual factors within urban and rural places. There are both challenges and opportunities presented by urban and rural environments in promoting the health and well-being of all.

## Defining Migration

**Migration serves as both a cause and an effect of place**. As a cause, migration can reshape the demographic and socioeconomic composition of a place by introducing new populations with distinct attributes and needs, thereby influencing local resources, services, and social structures. For instance, an influx of migrants can stimulate economic growth, diversify cultural landscapes, and alter housing demands, thereby transforming the contextual characteristics of the destination. Conversely, migration is also an effect of place, driven by the push and pull factors inherent in the geographical, economic, and social environments of both origin and destination locations. Factors such as job opportunities, living conditions, environmental quality, and social networks can either attract or repel individuals from certain places, making migration a response to the existing contextual and compositional features of a location. Thus, understanding migration requires a dual perspective that acknowledges how places shape and are shaped by the movement of people.

Throughout this dissertation, we refer to migration as the movement of people between places within a country. We do not attempt to measure or quantify international migration, nor are we able to account for forced migration, displacement, or other forms of involuntary migration. <!--# need to say something here about county-level, individual-level, or household-level?? how to define irs data which counts households moving between counties -->

Theories of migration provide valuable frameworks for understanding how migration influences the health of individuals and communities within places. These theories, when applied to internal migration, offer insights into both the contextual and compositional measures of health in a place. <!--# need something about bimodality here??? -->

Economic theories of internal migration focus on wage and employment opportunities as primary drivers of migration. According to **macroeconomic models**, individuals move from regions with surplus labor and low wages to areas with labor shortages and high wages, and in some cases, individuals move because they have particular skills that are more highly rewarded in specific regions [@borjas1992]. This movement can impact the health of both the sending and the receiving places. In sending areas, the outmigration of working-age individuals can lead to a shortage of healthcare providers and caregivers (a compositional factor of place), adversely affecting community health. Conversely, receiving areas may experience increased demand for healthcare services, which can strain existing resources but also lead to improvements in healthcare infrastructure due to increased funding and investment (compositional change resulting in contextual change) [@vasile2023]. <!--# excluding remittances, dual labor market theory, and world systems theory -->

**Network theory** explains how social connections facilitate migration by reducing costs and risks associated with moving​​. Previous patterns of migration can be used to predict future patterns of migration [@lorincz2019], suggesting that individual-level migration has implications for group-level migration. Additionally, in one study of internal migration in Austria, over 60% of migration flows were reciprocated, meaning that there was effectively an exchange of individuals from one region to another [@pitoski2021]. Similarly, return migration can lead to a "propogation effect" in which behaviors and health conditions from a destination of migration can change behaviors and health conditions in an origin of migration [@ginsburg2016]. Therefore, migrant networks can play a crucial role in health outcomes of migrants in both destination and origin places. Migrant networks can provide social support and information about healthcare services in destination areas and enhance migrants' access to healthcare by connecting them with resources and community support. However, reliance on informal networks can also lead to disparities in healthcare access and quality, particularly if migrants are excluded from formal healthcare systems due to legal or socioeconomic barriers​ [@vasile2023].

**Cumulative causation theory** suggests that migration creates conditions that make further migration more likely​ ([SpringerLink](https://link.springer.com/chapter/10.1007/978-3-031-18683-7_3))​. This theory can explain how health disparities in sending regions may worsen over time as migration depletes the local human capital, including healthcare professionals. The loss of skilled health workers can reduce the quality and availability of healthcare services in these areas. Conversely, receiving regions may experience improvements in healthcare infrastructure due to increased demand, but also face challenges related to integrating diverse populations with varying health needs​ ([SpringerLink](https://link.springer.com/chapter/10.1007/978-3-031-18683-7_3))​.

**Migration systems theory** integrates various migration theories, positing that migration flows become stable over time, creating specific migration systems characterized by intense exchanges between certain regions​ ([SpringerLink](https://link.springer.com/chapter/10.1007/978-3-031-18683-7_3))​. This perspective is useful in understanding how longstanding migration patterns influence health outcomes in both sending and receiving areas, shaping healthcare needs and policies over time. Stable migration systems can lead to the development of tailored health services and policies that address the specific needs of migrant populations and improve overall community health​ ([SpringerLink](https://link.springer.com/chapter/10.1007/978-3-031-18683-7_3))​.

These theories of migration provide a comprehensive framework for understanding the complex interplay between migration and health. They highlight how migration driven by economic, social, and structural factors can influence health outcomes through changes in healthcare access, socioeconomic conditions, and social support systems in both sending and receiving regions.

## Policy Implications

Urbanicity, migration, and environmental stressors each present unique challenges that require tailored public health strategies. A common thread is the recognition that both structural and compositional aspects of place are inherently intertwined and must be addressed together to effectively reduce health disparities.

From a policy-lens, this means developing interventions sensitive to the specific contextual and compositional realities of different populations. In urban areas, improving the built environment and ensuring equitable access to resources can mitigate mental health disparities. In regions experiencing significant migration, policies should focus on supporting both the structural needs of receiving and sending communities and the health needs of migrants.

By integrating findings from diverse contexts, this dissertation highlights the necessity of a holistic approach to public health research and policy. The interrelationships between geography, migration, and health outcomes are critical areas of study that offer valuable insights for public health interventions. This dissertation addresses several key problems related to these themes, focusing on how geographical factors, migration, and environmental stressors affect mental health and overall health outcomes across different populations.

Addressing health disparities requires an understanding of how place-based structural factors and individual characteristics interact to shape health outcomes. The common threads that run through the three chapters of this dissertation include the exploration of urbanicity, the impact of migration on health metrics, and the unique challenges faced by vulnerable populations in different geographical contexts.

The chapters in this dissertation collectively emphasize the complex interplay between geographical factors, migration, and health outcomes, incorporating both contextual and compositional measures. By examining these relationships in different contexts, this work contributes to a deeper understanding of how place and movement influence health. The insights gained from these studies can guide the development of targeted public health policies and interventions aimed at improving health outcomes and reducing disparities across diverse populations. By addressing both the structural environment and the characteristics and movements of the population, policymakers can create more effective and equitable health strategies.

## Specific Aims

The first chapter of this dissertation examines the influence of urbanicity on mental health in US counties, aiming to quantify contemporary relationships between the built environment and self-reported poor mental health days. The second chapter shifts the focus to migration, investigating how county-to-county migration flows influence average health metrics and the potential misattribution of health outcome changes when migration is not considered in models. The third chapter builds on these themes by exploring the interactions between migration patterns and premature age-adjusted mortality rates, using tensor decomposition techniques to uncover how spatial and temporal migration flows may contribute to health disparities across US counties.

**Chapter 1: Urbanicity and Mental Health in US Counties**

Geography may influence mental health by inducing changes in social, physical, and health-related environmental factors. This chapter seeks to quantify contemporary relationships between urbanicity and self-reported poor mental health days across US counties, incorporating both contextual and compositional measures. Using data from the County Health Rankings and Roadmaps, regression analyses were performed on 3,142 US counties, controlling for contextual variables such as state, income, and education, as well as compositional factors like age and race/ethnicity. Findings indicate that large central metro counties report fewer average poor mental health days compared to small metro counties, with differences partially mediated by contextual factors such as the built environment, including better food environments. Conversely, noncore counties report more poor mental health days, with these disparities not mediated by considered factors. These results highlight the need for tailored public health strategies that address specific urban and rural mental health challenges, taking into account both the structural environment and the composition of the population.

**Chapter 2: Migration and Health Outcomes in US Counties**

This chapter investigates the impact of migration on county-level health outcomes in the United States, emphasizing the importance of considering compositional changes due to migration when analyzing health metrics alongside contextual county characteristics. Using mortality data from CDC WONDER and migration flow data from the IRS, the study develops novel extensions of autoregressive spatial error models to incorporate migration flows. The analysis focuses on premature age-adjusted mortality rates from 2011 to 2019, examining the influence of migration and urbanicity. The findings reveal that migration significantly improves the explainability of models for county-level health outcomes, showing that compositional changes in population due to migration, alongside contextual factors such as local healthcare infrastructure, are critical for understanding health disparities. By accounting for migration flows and health-related selection of migrants, the study provides a comprehensive understanding of the dynamic relationship between migration and health outcomes, informing more precise public health policies.

**Chapter 3: Spatio-temporal analysis of county-to-county migration patterns on premature mortality**

This study examines the relationship between county-level migration patterns and premature age-adjusted mortality rates in the contiguous United States, utilizing a comprehensive spatio-temporal modeling approach. By applying Canonical Polyadic (CP) tensor decomposition to IRS county-to-county migration data from 2011 to 2019, we capture complex migration flows and their effects on health outcomes. Our analysis identifies distinct migration systems and explores how origin, destination, and temporal components contribute to variations in mortality rates across counties.

Through spatial panel modeling, we demonstrate that migration patterns significantly influence health outcomes, with counties experiencing higher outmigration often facing elevated premature mortality. In contrast, certain migration flows are associated with improved health outcomes, highlighting the dual role of migration in either exacerbating or mitigating health disparities. By integrating contextual (geographical) and compositional (demographic) dimensions of place-based health, we underscore the importance of spatial and temporal factors in understanding migration’s impact on health equity. These findings suggest targeted public health interventions are necessary to address health disparities in regions with significant migration, particularly in areas with high outmigration.
