---
title: "README"
output: pdf_document
date: "2024-09-18"
---

Abstract

Throughout this dissertation, we explore the interconnected impacts of migration and urbanicity on place-based health determinants across the United States. Traditional place-based health measures often overlook the dynamic influence of migration, while conventional migration studies typically do not assess the broader place-level health impacts on origin and destination locations. By examining contextual (structural) and compositional (individual) factors, we assess how migration flows influence local health outcomes across varying urban and rural environments. Using publicly accessible county-level data and IRS migration flow records, we highlight how urbanicity and migration patterns together shape place-based health disparities, with special emphasis on mental health, premature mortality, and socioeconomic factors. Employing advanced spatial and tensor decomposition models, we aim to provide insight into the dynamics of population health, offering implications for localized health policy interventions and resource allocation across diverse communities.



To do: 

XXX Double space pdf output 
- switch screenshot tables to something better?  
XXX check all citations 
XXX make sure in-text citations look nice 
- check format of citations - what did ken and megan use? 
XXX need one mega citations list 
- move page numbers to top right 
- check other UW formatting specifics to match 
XXX check the whole document for "CITE" 

- Appendix A: 
    -XXX titles/ links of tables are misaligned 
    -XXX make sure in-text tables are linked instead of appendix tables (tables 1:4) 

- Aim 2: 
    -XXX create aic table for appendix 
    -XXX make table 1 readable/ formatted correctly for pdf 

- Aim 3: 
    - more about padj? 
    
- Intro: 
    - venn diagram?  

